export const SET_OBC_AMPS = 'SET_OBC_AMPS';
export const SET_OBC_VOLTS = 'SET_OBC_VOLTS';
export const SET_CAMERA_AMPS = 'SET_CAMERA_AMPS';
export const SET_CAMERA_VOLTS = 'SET_CAMERA_VOLTS';

export const CHANGE_OBC_CONNECTION = 'CHANGE_OBC_CONNECTION';
export const CHANGE_CAMERA_CONNECTION = 'CHANGE_CAMERA_CONNECTION';
